name: capstone_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  rxdart: ^0.24.0
  http: ^0.12.0+1
  equatable: ^1.2.5
  flutter_bloc: ^6.1.0
  google_fonts: ^1.1.0
  hydrated_bloc: ^6.0.0
  json_annotation: ^3.0.1
  pedantic: ^1.9.0
  meta: ^1.1.8
  uuid: ^2.1.0
  formz: ^0.3.2
  lorem_ipsum: ^0.0.1
  modal_bottom_sheet: ^1.0.0+1
  skeleton_loader: ^1.0.2+2
  image_picker: 0.6.7+22
  dio: ^3.0.10
  gallery_saver: ^2.0.3
  cool_alert: ^1.0.3
  firebase_core: "^0.5.0+1"
  firebase_messaging: "^7.0.3"
  dropdownfield: 0.0.2
  circular_check_box: ^1.0.4
  flag: ^3.2.2
  flutter_localizations:
    sdk: flutter
  month_picker_dialog: ^0.3.3
  intl: ^0.16.1
  date_util: ^0.1.4
  multi_image_picker: ^4.6.5
  flutter_local_notifications: ^1.4.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  build_runner: ^1.10.0
  json_serializable: ^3.4.0
  mockito: ^4.0.0
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo.png"
  image_path_android: "assets/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyIcons
      fonts:
        - asset: assets/icons/MyIcons.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
        
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
